spring:
  application:
    name: garcom-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

kafka:
  topic:
    pedido-criado: pedido-criado