spring:
  application:
    name: garcom-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml